spring:
 application:
  name: Review-Service
 cloud:
  nacos:
   server-addr: 192.168.50.134:8848
   config:
    import-check:
     enabled: false
  sentinel:
   transport:
    dashboard: 192.168.50.134:8858
   http-method-specify: true
 rabbitmq:
  host: 192.168.50.134
  port: 5672
  username: root
  password: 111600
  virtual-host: /
  listener:
   direct:
    prefetch: 1
    acknowledge-mode: auto #消费者确认机制,通过抛出不同类型的异常来给出不同的返回值，来确认是否要删除队列中的消息
    retry:
     stateless: false #如果消息含有事务,改为false，设置为有状态
     enabled: true
     max-attempts: 3
 datasource:
  url: jdbc:mysql://localhost:3306/volunteer_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  username: root
  password: 111600
  driver-class-name: com.mysql.cj.jdbc.Driver
 servlet:
  multipart:
   enabled: true
   max-file-size: 5MB
   max-request-size: 10MB
logging:
 level:
  org.springframework.ai: DEBUG
  org.springframework.ai.chat.client.advisor: debug
  org.springframework.ai.tool: debug
  org.springframework.ai.chat.client: debug
xxl:
 job:
  admin:
   addresses: http://127.0.0.1:8090/xxl-job-admin
  executor:
   appname: Review-service
   port: 9993
  accessToken: default_token
server:
 port: 8087
